config/routes.rb
NestedResources::Application.routes.draw do
  devise_for :users
  root to: 'posts#index'

  post "/posts/:post_id/comments/:id", to: "comments#create_comment", as: "create_comment"

  resources :posts do
    resources :comments, only: [:show, :create]
  end

#   Prefix Verb   URI Pattern                            Controller#Action
#         new_user_session GET    /users/sign_in(.:format)               devise/sessions#new
#             user_session POST   /users/sign_in(.:format)               devise/sessions#create
#     destroy_user_session DELETE /users/sign_out(.:format)              devise/sessions#destroy
#            user_password POST   /users/password(.:format)              devise/passwords#create
#        new_user_password GET    /users/password/new(.:format)          devise/passwords#new
#       edit_user_password GET    /users/password/edit(.:format)         devise/passwords#edit
#                          PATCH  /users/password(.:format)              devise/passwords#update
#                          PUT    /users/password(.:format)              devise/passwords#update
# cancel_user_registration GET    /users/cancel(.:format)                devise/registrations#cancel
#        user_registration POST   /users(.:format)                       devise/registrations#create
#    new_user_registration GET    /users/sign_up(.:format)               devise/registrations#new
#   edit_user_registration GET    /users/edit(.:format)                  devise/registrations#edit
#                          PATCH  /users(.:format)                       devise/registrations#update
#                          PUT    /users(.:format)                       devise/registrations#update
#                          DELETE /users(.:format)                       devise/registrations#destroy
#                     root GET    /                                      posts#index
#            post_comments POST   /posts/:post_id/comments(.:format)     comments#create
#             post_comment GET    /posts/:post_id/comments/:id(.:format) comments#show
#                    posts GET    /posts(.:format)                       posts#index
#                          POST   /posts(.:format)                       posts#create
#                 new_post GET    /posts/new(.:format)                   posts#new
#                edit_post GET    /posts/:id/edit(.:format)              posts#edit
#                     post GET    /posts/:id(.:format)                   posts#show
#                          PATCH  /posts/:id(.:format)                   posts#update
#                          PUT    /posts/:id(.:format)                   posts#update
#                          DELETE /posts/:id(.:format)                   posts#destroy



end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id               :integer          not null, primary key
#  body             :string(255)
#  post_id          :integer
#  user_id          :integer
#  commentable_id   :integer
#  commentable_type :string(255)
#  created_at       :datetime
#  updated_at       :datetime
#

class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user

  belongs_to :commentable, polymorphic: true
  has_many :comments, as: :commentable
end

app/models/nested_resources_dev.rb
class NestedResourcesDev < ActiveRecord::Base
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  link       :string(255)
#  body       :text
#  user_id    :integer
#  created_at :datetime
#  updated_at :datetime
#

class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments, as: :commentable, dependent: :destroy
  accepts_nested_attributes_for :comments
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime
#  updated_at             :datetime
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts, dependent: :destroy
  has_many :comments
end

app/models/vote.rb
class Vote < ActiveRecord::Base
	belongs_to :comment
	belongs_to :post

	def upvote
		self.increment!(:count)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception








end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :authenticate_user!
  def show
    @comment = Comment.find(params[:id])
    @post = Post.find(params[:post_id])
  end

  def create
    post = Post.find(params[:post_id])
    comment = post.comments.create(params[:comment].permit(:body))
    current_user.comments << comment
    redirect_to post_path(post)
  end

  def create_comment
    comment = Comment.find(params[:id])
    new_comment = comment.comments.create(params[:comment].permit(:body))
    current_user.comments << new_comment
    redirect_to post_comment_path(params[:post_id], comment.id)
  end

end

app/controllers/concerns/comments_controller.rb
class CommentsController < ApplicationController

	def index
		@post = Post.find(params[:post_id])
		# @highest_bid = Auction.find(params[:auction_id]).bids.maximum('amount')
	end
	def show
		@post = Post.find(params[:post_id])
		@comment = @post.comments.find(params[:id])
	end

	def new
		@post = Post.find(params[:post_id])
		@comment = @post.comments.new
	end

	def create
		new_comment = params[:comment].permit(:body)
		post = Post.find(params[:post_id])
		comment = post.comments.create(new_comment)
		redirect_to post_comment_path(post, comment)
	end

	def edit
		@post = Post.find(params[:post_id])
		@comment = @post.comments.find(params[:id])
	end

	def update
		# edit_bid = params[:bid].permit(:amount)
		# auction = Auction.find(params[:auction_id])
		# bid = auction.bids.find(params[:id])
		# bid.update_attributes(edit_bid)

		# # redirect_to auction_bid_path
		# # below link also works
		# redirect_to [auction, bid]
	end


	def delete
		# @auction = Auction.find(params[:auction_id])
	end


end

app/controllers/concerns/users_controller.rb
users_controller.rb

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticate_user!
  def index
    @posts = current_user.posts
  end

  def new
    @post = Post.new 
  end

  def create
    post_params = params.require(:post).permit(:link, :body, comments_attributes: [ :body ])
    post = current_user.posts.create(post_params)
    LinksWorker.perform_async(post.id)
    redirect_to posts_path
  end

  def show
    @post = current_user.posts.find(params[:id])
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def index
  end

  def show
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  	@users = User.all
  end

  def new
  	@user = User.new
  end


  def show
  	@user = User.find(params[:id])
  end

  def edit
  	@user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def print_comments(comment, tab=0)
    puts "\t"*tab + comment.body
    unless comment.comments.blank?
      tab += 1
      comment.comments.each do |c|
        print_comments(c, tab)
      end
    end
    nil
  end
  
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/comments/_comment.html.erb
<div class="comment"><%= comment.body %> by <%= comment.user.email %> at <%= comment.created_at %>
    <% if user_signed_in? %>
            <a href="<%= new_comment_comment_path(comment.id)%>">Comment</a> </br>
    <% else %>
            <a href="<%= new_user_session_path %>">Login to comment</a></br>
    <% end %>
<%= render comment.comments if comment.comments.length > 0 %></div>

app/views/comments/_comments.html.erb
<div id="comments">
  <% @comments.each do |comment| %>
    <div class="comment">
      <%= simple_format comment.body %>
    </div>
  <% end %>
</div>

app/views/comments/_form.html.erb
<div class="container form">
	<%= form_for [@post, @comment] do |p| %>
		<%= p.text_area :body, placeholder: "write a comment..." %>
		<%= p.submit %>
	<% end %>
</div>

app/views/comments/_nav.html.erb
<ul class="nav nav-pills nav-stacked">
  <li class="active">
  	<%= link_to "Posts", root_path %>
  </li>
   <li>
  	<%= link_to "Posts", root_path %>
  </li>

</ul>

app/views/comments/_new_comment.html.erb
<%= form_for [@post, @new_comment] do |f| %>
  <%= f.text_area :body %>
  <% f.hidden :type, value = @comment_type %>
  <% f.hidden :id, value = params[:id] %>
  <%= f.submit %>
<% end %>

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

app/views/comments/edit.html.erb
<h1> Edit me </h1>

<%=form_for [@post, @comment] do |f| %>
<%= f.text_field :commentbody %>
<%= f.submit %>
<%end%>

app/views/comments/index.html.erb
<h1>Comments#index</h1>
<p>Find me in app/views/comments/index.html.erb</p>

app/views/comments/new.html.erb
<h1>Comments#new</h1>
<p>Find me in app/views/comments/new.html.erb</p>

<%= form_for [@post, @comment] do |f| %>

<%= f.text_area :body, placeholder: "Comments" %>

<%= f.submit %>

<% end %>

app/views/comments/show.html.erb
  <h4>Comments:</h4>
  <h5><%= @comment.body %></h5>

  <% @comment.comments.each do |comment| %>
    <div><a href="<%= post_comment_path(@post.id, comment.id)%>"><%= comment.body %></a></div>
  <% end %>



<%= form_for :comment, url: create_comment_path(@post.id, @comment.id), method: :post do |f| %>
    <%= f.text_area :body, placeholder: "Enter comment", value: nil %><br>
    <%= f.submit "Submit Comment on Comment" %>
  <% end %>

app/views/comments/update.html.erb
<h1>Comments#update</h1>
<p>Find me in app/views/comments/update.html.erb</p>

app/views/layouts/_heading.html.erb
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Studdit</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li>
              <%= link_to current_user.email, "#" %>
            </li>
            <li>
              <%= link_to('Log out', destroy_user_session_path, :method => :delete) %>
            </li>        
          <% else %>
            <li>
            <%= link_to('Log in', new_user_session_path)  %>  
            </li>
            <li>
            <%= link_to('Sign up', new_user_registration_path) %>  
            </li>
          <% end %>
        </ul>
        </div><!--/.navbar-collapse -->
      </div>
    </div>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "danger" %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_nav.html.erb
<div class='navbar navbar-fixed-top'>
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.&nbsp;&nbsp;
  <%= link_to 'Home', root_path, :class => 'navbar-link' %>  |  
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %>  |  
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'%>  |  
  <%= link_to "Create a post", new_post_path, method: :get, :class => 'navbar-link'  %>
<% else %>
  <%= link_to 'Home', root_path, :class => 'navbar-link' %>  |  
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>

app/views/layouts/_nav_bar.html.erb
<nav class="navbar navbar-inverse" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button><a class="navbar-brand" href="/">Sorta Reddit!</a>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav">
      <!-- <li><a href="/">some link.</a></li> -->
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
        <li><%= link_to ("Welcome " + current_user.email + "!"), edit_user_registration_path %></li>
        <li><%= link_to "Edit profile", edit_user_registration_path %></li>
        <li><%= link_to "Sign out", destroy_user_session_path, method: "delete" %></li>
      <% else %>
        <li><%= link_to "Sign up", new_user_registration_path %></li>
        <li><%= link_to "Sign in", new_user_session_path %></li>
      <% end %>
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>

app/views/layouts/_navigation.html.erb
<ul class="nav nav-sidebar">
	<li class="active">
		<%= link_to "Posts", root_path %>
	</li>
	<li class="active">
		<a href="/posts/new"><span class="glyphicon glyphicon-plus"></span></a>
	</li>
</ul>

<ul class="nav nav-sidebar">
	<% if signed_in? %>
		<li>
			<%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
		</li>
	<% else %>
		<li>
			<%= link_to "Sign in", new_user_session_path %>
		</li>
	    <li>
	  		<%= link_to "Sign up", new_user_registration_path %>
	  	</li>
	<% end %>

</ul>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/_post.html.erb
_post.html.erb

<!-- a post, with a potentially nested comment  -->
<%= form_for [@post, @comment] do |f| %>  

	<%= f.text_field :body, :placeholder => "what's on your mind"%>
	<%= f.text_field :link, :placeholder => "add your sweet link"%>

	<%= f.submit "post" %>
<%= end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NestedResources</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<% unless current_user %>
	<%= form_for(:user, :url => session_path(:user)) do |f| %>
		<%= f.text_field :email %>
		<%= f.password_field :password %>
		<%= f.submit 'Sign in' %>

	<% end %>
	<% end %>

<%= button_to "Log Out", destroy_user_session_path, method: :delete %>
<%= yield %>

</body>
</html>

app/views/posts/_comment.html.erb
<%= comment.comment_body %><%= link_to "View Comment", comment_comment_path(@comment, comment) %><br> blah blah 

app/views/posts/_form.html.erb
<div class"container form">
	<%= form_for @post do |p| %>
		<%= p.text_field :link, placeholder: "paste link here" %>
		<%= p.text_field :body, placeholder: "what is on your mind?" %>
		<%= p.submit %>
	<% end %>
</div>

app/views/posts/create.html.erb
<h1>Add a post</h1>
<%= form_for @post do |f| %>
  <%= f.text_field :link, placeholder: "Name of link" %>
  <%= f.fields_for :comments, @post.comments.build do |b| %>
    <%= b.text_field :body, placeholder: "Add a comment" %>
    <% end %>
    <%= f.submit %>
<% end %>

app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

app/views/posts/edit.html.erb
<%= link_to "Back", post_path(@post) %>
<h1>Edit Post:</h1>

<%= form_for @post do |f| %>
	<%= f.text_field :link, placeholder: "link" %><br>
	<%= f.text_area :body, placeholder: "Post body" %><br>
	<%= f.submit %>
<% end %>
<%= button_to "Delete post", action: "destroy" %>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
  <div>
    <div><a href="<%= post_path(post) %>"><%= post.link %></a></div>
    <div><%= post.body %></div>
  </div>
<% end %>

app/views/posts/new.html.erb
<%= form_for @post do |f| %>
  <%= f.label :link %>
  <%= f.text_field :link %> 
  <%= f.label :body %>
  <%= f.text_field :body %> 
  <%= f.fields_for :comments, @post.comments.build do |c| %>
    <%= c.label :body, 'Comment text' %>
    <%= c.text_field :body %>
  <% end %>
  <%= f.submit "Add" %>
<% end %>

app/views/posts/show.html.erb
<h2>My Posts</h2>
<div>Post link: <%= @post.link %></div>
<div>Post body: <%= @post.body %></div><br>

<div>
  <h4>Comments:</h4>
  <% @post.comments.each do |comment| %>
    <div><a href="<%= post_comment_path(@post.id, comment.id)%>"><%= comment.body %></a></div>
      


  <% end %>
</div>

<%= form_for :comment, url: "/posts/#{@post.id}/comments", method: :post do |f| %>
    <%= f.text_area :body, placeholder: "Enter comment" %><br>
    <%= f.submit "Submit Comment" %>
  <% end %>

app/views/posts/update.html.erb
<h1>Posts#update</h1>
<p>Find me in app/views/posts/update.html.erb</p>

app/views/profiles/index.html.erb
<h1>Profiles#index</h1>
<p>Find me in app/views/profiles/index.html.erb</p>

app/views/profiles/show.html.erb
<h1>Profiles#show</h1>
<p>Find me in app/views/profiles/show.html.erb</p>

app/views/shared/_bylines.html.erb
<p class="comment-count">Posted by <%= post.author %> (<%= pluralize(post.comment_count, "comment") %>)</span>

app/views/shared/_comment.html.erb
<li class="comment-wrap alert-warning">
<h5>
	<% if comment.commentable.is_a?(Post) %>
		<%= link_to comment.author, post_comment_path(comment.commentable, comment) %> 
	<% else %>
		<%= link_to comment.author, comment_comment_path(comment.commentable, comment) %> 
	<% end %>  says...</h5>
<div class="comment-body">
	<%= comment.body %>
</div>
<p class="reply-btn"><%= link_to "Reply", new_comment_comment_path(comment), class: "btn btn-success btn-xs" %></p>
</li>
<% unless comment.comments.empty? %>
	<ul class= "comment_list">
		<%= render partial: 'shared/comment', collection: comment.comments.order(created_at: :asc) %>
	</ul>
<% end %>

app/views/shared/_post.html.erb
<div class="post-list">
	
	<!-- Post -->
	<%= render partial: 'shared/post_head', locals: { post: post } %>
	<p><%= link_to "Comment", new_post_comment_path(post), class: "btn btn-success btn-xs" %></p>

	<!-- Comments -->
	<h3>Comments</h2>
	<ul class="comment_list">
		<%= render partial: 'shared/comment', collection: post.comments.order(created_at: :asc) %>
	</ul>

</div>

app/views/shared/_post_head.html.erb
<h1 class="page-heading"><%= link_to post.body, post_path(post) %></h1>
<p><%= link_to post.link, post.link %></p>
<%= render partial: 'shared/bylines', locals: { post: post } %>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/show.html.erb
<h1><%= @user.name %>'s posts </h1>

<% @posts.each do |p| %>
  <ul>
    <li> <%= link_to p.body, post_path(p) %></li>
    <li><%= p.link%></li>
  </ul>
<% end %>